### ISSUE TITLE
Fix warning 'default.stringAsFactors' is deprecated

### ISSUE THREAD

**Issue by mrustl** [KWB-R/kwb.utils#35]
https://github.com/KWB-R/kwb.utils/runs/6625485980?check_suite_focus=true

![Screenshot_2022-05-27-14-46-56-003_com android chrome](https://user-images.githubusercontent.com/11964451/170702123-f00d1b25-98ae-4e35-a144-4c680c51ed5c.jpg)

**Comment by hsonne** [comment]
Done with 7a51119fac9a9f82456e26950c49b60c346af191
